"""
Multi-Agent Orchestrator: Master Agency Pipeline
Coordinates the 5 specialized agents to deliver high-converting marketing campaigns,
and connects the autonomous Media Buyer for 24/7 ad account optimization.
"""

import time
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

from agents.avatar_researcher import AvatarResearcherAgent
from agents.seo_strategist import SEOStrategistAgent
from agents.copywriter_elite import CopywriterEliteAgent
from agents.creative_director import CreativeDirectorAgent
from agents.agency_director import AgencyDirectorAgent
from agents.media_buyer_bot import MediaBuyerBot

logger = logging.getLogger("AgencyOrchestrator")
console = Console()

OUTPUTS_DIR = Path(__file__).resolve().parent / "outputs"
OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

class AgencyOrchestrator:
    def __init__(self):
        self.researcher = AvatarResearcherAgent()
        self.seo = SEOStrategistAgent()
        self.copywriter = CopywriterEliteAgent()
        self.creative_director = CreativeDirectorAgent()
        self.agency_director = AgencyDirectorAgent()
        self.media_buyer = MediaBuyerBot()

    def run_full_campaign(self, niche: str, location: str, offer: str) -> Dict[str, Any]:
        """Runs the 5-Agent Pipeline to generate a complete ready-to-launch campaign."""
        console.rule("[bold cyan]🚀 INITIATING 5-AGENT DIGITAL MARKETING CAMPAIGN PIPELINE[/bold cyan]")
        console.print(f"[bold]Target Niche:[/bold] {niche} | [bold]Geo:[/bold] {location}")
        console.print(f"[bold]Core Offer:[/bold] {offer}\n")

        bundle = {}

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            transient=True
        ) as progress:

            # 1. Market Research & Avatar Psychology
            t1 = progress.add_task("[cyan]Agent 1: Extracting Psychological Avatar & Competitor Intel...", total=None)
            bundle["research"] = self.researcher.analyze_market(niche, location, offer)
            progress.remove_task(t1)
            console.print("  ✅ [green]Agent 1 (Market Researcher):[/green] Persona & Pain Points locked in.")

            # 2. SEO & High-Intent Search Architecture
            t2 = progress.add_task("[cyan]Agent 2: Mapping High-Intent Keywords & Negative Lists...", total=None)
            bundle["seo"] = self.seo.formulate_strategy(niche, location, offer, bundle["research"])
            progress.remove_task(t2)
            console.print("  ✅ [green]Agent 2 (SEO Strategist):[/green] Commercial intent & Negative keywords ready.")

            # 3. Direct-Response Copywriting
            t3 = progress.add_task("[cyan]Agent 3: Crafting 3x Meta Ads & 5x Viral Reel Scripts...", total=None)
            bundle["copy"] = self.copywriter.write_campaign_copy(niche, location, offer, bundle["research"])
            progress.remove_task(t3)
            console.print("  ✅ [green]Agent 3 (Copywriter Elite):[/green] High-converting ad copy & scripts drafted.")

            # 4. Visual Direction & Art Assets
            t4 = progress.add_task("[cyan]Agent 4: Designing Visual Blueprints & Image Generation Prompts...", total=None)
            bundle["visuals"] = self.creative_director.create_visual_specs(niche, location, bundle["copy"])
            progress.remove_task(t4)
            console.print("  ✅ [green]Agent 4 (Creative Director):[/green] Visual specs, prompts & B-roll cues generated.")

            # 5. Agency Director & CMO Quality Gate
            t5 = progress.add_task("[cyan]Agent 5: Executive CMO Fluff Audit & Meta Policy Review...", total=None)
            bundle["cmo_review"] = self.agency_director.review_and_finalize(niche, location, bundle)
            progress.remove_task(t5)
            console.print("  ✅ [green]Agent 5 (Agency Director):[/green] Ruthless audit completed & approved.\n")

        # Compile Master Markdown Document
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_niche = "".join(c for c in niche if c.isalnum() or c in (' ', '_', '-')).rstrip().replace(' ', '_').lower()
        output_file = OUTPUTS_DIR / f"campaign_{safe_niche}_{timestamp}.md"

        full_document = f"""# Master Campaign Dossier: {niche} ({location})
**Generated by WholeUp Agency Multi-Agent Growth System**
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Offer:** {offer}

---

## 1. Executive Summary & CMO Review
{bundle['cmo_review']}

---

## 2. Psychological Avatar & Market Intelligence
{bundle['research']}

---

## 3. SEO & High-Intent Search Blueprint
{bundle['seo']}

---

## 4. Direct Response Copywriting (3 Meta Ads + 5 Viral Reels)
{bundle['copy']}

---

## 5. Visual Art Direction, Image Prompts & B-Roll Blueprint
{bundle['visuals']}

---
*Generated with 5+ Year Direct Response Growth Heuristics.*
"""

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(full_document)

        console.print(f"[bold green]🎉 MASTER CAMPAIGN FILE EXPORTED:[/bold green] {output_file}\n")
        bundle["file_path"] = str(output_file)
        return bundle

    def run_ad_autopilot(self, dry_run: bool = False) -> Dict[str, Any]:
        """Runs the 24/7 Autonomous Ad Optimizer to Kill Bleeders and Scale Winners."""
        console.rule("[bold red]🤖 EXECUTING AUTONOMOUS AI MEDIA BUYER & AD OPTIMIZER[/bold red]")
        result = self.media_buyer.evaluate_and_optimize(dry_run=dry_run)
        return result
